### ISSUE TITLE
Error: spawnSync /bin/sh ENOBUFS

### ISSUE THREAD

**Issue by gioxx** [AlexHolderDeveloper/CommitsWithinTime#5]
Ciao @AlexStormwood,
processes using your Action all failed today because of this error:

```
node:child_process:902
    throw err;
    ^

<ref *1> Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:814:24)
    at execSync (node:child_process:894:15)
    at getGitRevMegaString (/home/runner/work/_actions/AlexHolderDeveloper/CommitsWithinTime/v1.1.11/src/index.js:71:12)
    at gatherInfoOnCommitsWithinTime (/home/runner/work/_actions/AlexHolderDeveloper/CommitsWithinTime/v1.1.11/src/index.js:76:35)
    at Object.<anonymous> (/home/runner/work/_actions/AlexHolderDeveloper/CommitsWithinTime/v1.1.11/src/index.js:243:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -105,
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: [
    '-c',
    'git rev-list --remotes --format="CommitHash:%H%nAuthor:%an%nEmail:%ae%nCommitterAuthor:%cn%nCommitterEmail:%ce%nDate:%ct%nMessage:%s"'
  ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    Buffer(1048773) [Uint8Array] [
      99, 111, 109, 109, 105, 116,  32,  57,  99,  98,  56,  56,
      48, 101,  54,  53,  97,  52, 101, 101,  49,  54,  97, 101,
      56,  57,  98,  53,  53, 102,  55,  52,  52,  54,  55,  51,
      50,  48,  97, 102,  97,  56,  55,  57,  56,  50,  51,  10,
      67, 111, 109, 109, 105, 116,  72,  97, 115, 104,  58,  57,
      99,  98,  56,  56,  48, 101,  54,  53,  97,  52, 101, 101,
      49,  54,  97, 101,  56,  57,  98,  53,  53, 102,  55,  52,
      52,  54,  55,  51,  50,  48,  97, 102,  97,  56,  55,  57,
      56,  50,  51,  10,
      ... 1048673 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 4638,
  stdout: Buffer(1048773) [Uint8Array] [
    99, 111, 109, 109, 105, 116,  32,  57,  99,  98,  56,  56,
    48, 101,  54,  53,  97,  52, 101, 101,  49,  54,  97, 101,
    56,  57,  98,  53,  53, 102,  55,  52,  52,  54,  55,  51,
    50,  48,  97, 102,  97,  56,  55,  57,  56,  50,  51,  10,
    67, 111, 109, 109, 105, 116,  72,  97, 115, 104,  58,  57,
    99,  98,  56,  56,  48, 101,  54,  53,  97,  52, 101, 101,
    49,  54,  97, 101,  56,  57,  98,  53,  53, 102,  55,  52,
    52,  54,  55,  51,  50,  48,  97, 102,  97,  56,  55,  57,
    56,  50,  51,  10,
    ... 1048673 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
```

**Comment by AlexStormwood** [comment]
Just as a sanity-check / confirmation on the workaround, the FLARE repository has almost 100k commits - far more than your xfiles repo - and they continue to use this action just fine with a fetch depth of 1 in their checkout step. 

[https://github.com/FLARE-forecast/FCRE-data/blob/main/.github/workflows/github-monitor-bita-logs.yml](https://github.com/FLARE-forecast/FCRE-data/blob/main/.github/workflows/github-monitor-bita-logs.yml)

**Comment by gioxx** [comment]
You are absolutely right, I needed to bring out a data for which I needed to have depth 0 (Was used to post a direct URL to the commit on Twitter, but since Twitter put the paid API and worsened the developer-side experience, I decided to remove the automatic tweets from GitHub and that data I don't need anymore, I cleaned up the code and brought depth to 1, now everything works properly).

Thank you so much as always!
Now all that remains is to close the issue regarding #4 😄
